### PR TITLE
added Bytes() to all types (Closes #35) 

### LINKED ISSUE #35: Serializing custom types
Each custom type (like [NodeID](https://github.com/filecoin-project/mir/blob/bb5838975558e5c51589411ca801a87721e1367d/pkg/types/types.go#L14) or [SeqNr](https://github.com/filecoin-project/mir/blob/bb5838975558e5c51589411ca801a87721e1367d/pkg/types/types.go#L52)) in the `types` package could have, in addition to the `Pb()` method, a `Bytes()` method that returns the value deterministically serialized into a slice of bytes.

### PR DESCRIPTION
**Pull request by ranchalp**
added function Bytes() to all types that return their serialization in a []byte slice.
Closes #35

### CODE REVIEW

**Review by matejpavlovic — CHANGES_REQUESTED** [review]
Great, thanks!

Just one little comment: Try sticking to the commit message formatting guidelines (nicely summarized [here](https://cbea.ms/git-commit/), for example). This is a "soft rule", it's good to follow it when possible.
To fix it, you can amend the commit (`git commit --amend`), rewrite the commit message, and force-push to the repo (`git push --force`).

**Comment by matejpavlovic** [comment]
I also see that the branch is out of date with the main branch in the original (upstream repo) and the linter is complaining about something. To fix that, you can
1. Rebase your branch on top of the upstream main branch ([see here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/configuring-a-remote-for-a-fork) for a convenient way of dealing with an upstream repository). Git seems to be suggesting to do that for you (the "Update branch" button), just make sure you don't create a merge commit, but rebase instead.
2. Running `make format` should satisfy the linter in this case I think.

**Comment by ranchalp** [comment]
Thanks for the requested changes, I have already addressed them.

**Comment by matejpavlovic** [comment]
The linter still complains, but this time about another issue. Sorry for this tedious workflow, it's only required for the very first PR, because I have to manually run the GitHub actions each time (it's GH's security measure). For all the next PRs, GitHub will do it automatically.

To run the linter locally, you can also run `make lint` locally (you might need to install golang-ci for that on your machine).

All this stuff I told you regarding this commit should have been already described in a "Contribution guide", sorry for that. It's on the todo list: #294

**Pull request merged**
